### ISSUE TITLE
https gives invalid cert error because it serves *.github.com

### ISSUE THREAD

**Issue by robintindale** [skpm/website#4]
error is `NET::ERR_CERT_COMMON_NAME_INVALID` because cert is for `*.github.com` domains.

depending on how `skpm.io` is set up, could serve a lets-encrypt cert

**Comment by robintindale** [comment]
ah I see how it's setup - probably isn't an easy way to serve a cert, other than using a proxy like https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by mathieudutour** [comment]
wait did I dream the announce that GitHub pages were supporting https for custom domains using let's encrypt? I can't find the blog post anymore.

I'm pretty sure I enabled it on developer.sketchapp.com which is a custom domain as well 🤔

**Comment by robintindale** [comment]
oo

> Hi ligi,
> 
> As you've discovered, some GitHub Pages sites have been issued SSL certificates from Let's Encrypt, enabling HTTPS for your custom domain. This isn't officially supported yet and it's not possible for you to enable and enforce it on your sites at this time.
> 
> We know how important secure browsing is for our users, but we don't have anything official to announce at this time. If and when this feature is officially released, we will announce it on our blog:
> 
> https://github.com/blog
> 
> Let us know if you have other questions!
> 
> Thanks,
> Thomas
> GitHub Support

source: https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8#gistcomment-2370070

**Comment by mathieudutour** [comment]
<img width="705" alt="screen shot 2018-04-16 at 16 32 33" src="https://user-images.githubusercontent.com/3254314/38815306-efd660ce-4193-11e8-9403-aff12af86f5f.png">
<img width="639" alt="screen shot 2018-04-16 at 16 32 50" src="https://user-images.githubusercontent.com/3254314/38815314-f2ee2eb8-4193-11e8-8439-4d2a93ecf072.png">

pretty sure they rolled back the feature 😢
Still enabled for developer.sketchapp.com tho

**Comment by robintindale** [comment]
not sure if they rolled it back - from that email it sounds like they're just rolling out slowly and unofficially, so hopefully this issue will get fixed without any action

**Comment by mathieudutour** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ :tada: 

Changing the DNS, should be all good very soon

**Comment by mathieudutour** [comment]
done!
